.test-radv:
  extends:
    - .test-vk
    - .radv-rules
  variables:
    VK_DRIVER: radeon
    DRIVER_NAME: radv
    # The SPIRV -> NIR code generator generates so many harmless
    # warnings on the shaders in VK-CTS that jobs fail due to the log
    # size getting too big. Since it doesn't seem feasible right now
    # to fix these shaders in the CTS, instead, ignore warnings from
    # the code generator.
    MESA_SPIRV_LOG_LEVEL: error
    ACO_DEBUG: validateir,validatera
    MESA_VK_IGNORE_CONFORMANCE_WARNING: 1

# Run three jobs in parallel each running 1/30th of the test suite
radv_stoney_vkcts:amd64:
  extends:
    - .lava-test:amd64
    - .radv-rules
  parallel: 3
  variables:
    DEQP_VER: vk
    DEQP_FRACTION: 10
    FDO_CI_CONCURRENT: 4
    DEQP_EXPECTED_RENDERER: STONEY
    DEVICE_TYPE: hp-11A-G6-EE-grunt
    DTB: ""
    GPU_VERSION: radv-stoney-aco
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
    HWCI_KERNEL_MODULES: amdgpu
    HWCI_FREQ_MAX: "true"
    VK_DRIVER: radeon
    DRIVER_NAME: radv
    RUNNER_TAG: mesa-ci-x86-64-lava-hp-11A-G6-EE-grunt

.radv-fossils:
  extends:
    - .fossilize-test
    - .test-radv
  script:
    # Pitcairn (GFX6)
    - export RADV_FORCE_FAMILY="PITCAIRN"
    - ./install/fossilize-runner.sh
    # Bonaire (GFX7)
    - export RADV_FORCE_FAMILY="BONAIRE"
    - ./install/fossilize-runner.sh
    # Polaris10 (GFX8)
    - export RADV_FORCE_FAMILY="POLARIS10"
    - ./install/fossilize-runner.sh
    # Vega10 (GFX9)
    - export RADV_FORCE_FAMILY="VEGA10"
    - ./install/fossilize-runner.sh
    # Navi10 (GFX10)
    - export RADV_FORCE_FAMILY="NAVI10"
    - ./install/fossilize-runner.sh
    # Sienna Cichlid (GFX10)
    - export RADV_FORCE_FAMILY="SIENNA_CICHLID"
    - ./install/fossilize-runner.sh
